apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: wordpress
  name: wordpress-np-svc
  namespace: user-17
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: wordpress