apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wordpress
  name: wordpress
  namespace: user-17
spec:
  containers:
  - image: wordpress
    imagePullPolicy: Always
    name: wordpress
    ports:
      - name: wordpress-port
        containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      valueFrom:
        secretKeyRef:
          name: wordpress-secret
          key: dbhost
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          name: wordpress-secret
          key: dbuser
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-secret
          key: dbpassword
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          name: wordpress-secret
          key: dbname